project_id = "sngdtpwpxpjfmkmqnuyi"

[functions.send-convite-email]
verify_jwt = true

[functions.send-pagamento-aprovado-email]
verify_jwt = true

[functions.send-pagamento-rejeitado-email]
verify_jwt = true

[functions.calcular-pontos]
verify_jwt = false

[functions.calcular-pontos-top4]
verify_jwt = true

[functions.gerar-boletim-diario]
verify_jwt = false

[functions.lembrete-palpite]
verify_jwt = false

[functions.send-capacidade-alerta]
verify_jwt = false

[functions.send-regras-signup]
verify_jwt = true

[functions.enviar-lembretes-diarios]
verify_jwt = false

[functions.enviar-boletim]
verify_jwt = true

[functions.enviar-errata-link]
verify_jwt = true

[functions.sync-match-scores]
verify_jwt = false

[functions.get-match-details]
verify_jwt = true

[functions.gerar-frases-do-dia]
verify_jwt = false

[functions.snapshot-top4-potenciais-iniciais]
verify_jwt = false
