/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as CadastroTokenRouteImport } from './routes/cadastro.$token'
import { Route as AppSimuladorRouteImport } from './routes/app.simulador'
import { Route as AppRankingRouteImport } from './routes/app.ranking'
import { Route as AppQuotasRouteImport } from './routes/app.quotas'
import { Route as AppPremioRouteImport } from './routes/app.premio'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppPalpitesRouteImport } from './routes/app.palpites'
import { Route as AppJogosRouteImport } from './routes/app.jogos'
import { Route as AppBoletinsRouteImport } from './routes/app.boletins'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppPalpitesTop4RouteImport } from './routes/app.palpites_.top4'
import { Route as AppPagamentoQuota_idRouteImport } from './routes/app.pagamento.$quota_id'
import { Route as AppAdminSaudeRouteImport } from './routes/app.admin.saude'
import { Route as AppAdminReportesRouteImport } from './routes/app.admin.reportes'
import { Route as AppAdminRelatoriosRouteImport } from './routes/app.admin.relatorios'
import { Route as AppAdminPremiacaoRouteImport } from './routes/app.admin.premiacao'
import { Route as AppAdminPerfisRouteImport } from './routes/app.admin.perfis'
import { Route as AppAdminPagamentosRouteImport } from './routes/app.admin.pagamentos'
import { Route as AppAdminJogosRouteImport } from './routes/app.admin.jogos'
import { Route as AppAdminConvitesRouteImport } from './routes/app.admin.convites'
import { Route as AppAdminConfiguracoesRouteImport } from './routes/app.admin.configuracoes'
import { Route as AppAdminBoletinsRouteImport } from './routes/app.admin.boletins'
import { Route as AppAdminAuditoriaRouteImport } from './routes/app.admin.auditoria'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CadastroTokenRoute = CadastroTokenRouteImport.update({
  id: '/cadastro/$token',
  path: '/cadastro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimuladorRoute = AppSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotasRoute = AppQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => AppRoute,
} as any)
const AppPremioRoute = AppPremioRouteImport.update({
  id: '/premio',
  path: '/premio',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPalpitesRoute = AppPalpitesRouteImport.update({
  id: '/palpites',
  path: '/palpites',
  getParentRoute: () => AppRoute,
} as any)
const AppJogosRoute = AppJogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => AppRoute,
} as any)
const AppBoletinsRoute = AppBoletinsRouteImport.update({
  id: '/boletins',
  path: '/boletins',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppPalpitesTop4Route = AppPalpitesTop4RouteImport.update({
  id: '/palpites_/top4',
  path: '/palpites/top4',
  getParentRoute: () => AppRoute,
} as any)
const AppPagamentoQuota_idRoute = AppPagamentoQuota_idRouteImport.update({
  id: '/pagamento/$quota_id',
  path: '/pagamento/$quota_id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSaudeRoute = AppAdminSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportesRoute = AppAdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRelatoriosRoute = AppAdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPremiacaoRoute = AppAdminPremiacaoRouteImport.update({
  id: '/premiacao',
  path: '/premiacao',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPerfisRoute = AppAdminPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPagamentosRoute = AppAdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminJogosRoute = AppAdminJogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminConvitesRoute = AppAdminConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminConfiguracoesRoute = AppAdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBoletinsRoute = AppAdminBoletinsRouteImport.update({
  id: '/boletins',
  path: '/boletins',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditoriaRoute = AppAdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/boletins': typeof AppBoletinsRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/palpites': typeof AppPalpitesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/premio': typeof AppPremioRoute
  '/app/quotas': typeof AppQuotasRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/simulador': typeof AppSimuladorRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/auditoria': typeof AppAdminAuditoriaRoute
  '/app/admin/boletins': typeof AppAdminBoletinsRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/convites': typeof AppAdminConvitesRoute
  '/app/admin/jogos': typeof AppAdminJogosRoute
  '/app/admin/pagamentos': typeof AppAdminPagamentosRoute
  '/app/admin/perfis': typeof AppAdminPerfisRoute
  '/app/admin/premiacao': typeof AppAdminPremiacaoRoute
  '/app/admin/relatorios': typeof AppAdminRelatoriosRoute
  '/app/admin/reportes': typeof AppAdminReportesRoute
  '/app/admin/saude': typeof AppAdminSaudeRoute
  '/app/pagamento/$quota_id': typeof AppPagamentoQuota_idRoute
  '/app/palpites/top4': typeof AppPalpitesTop4Route
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/boletins': typeof AppBoletinsRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/palpites': typeof AppPalpitesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/premio': typeof AppPremioRoute
  '/app/quotas': typeof AppQuotasRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/simulador': typeof AppSimuladorRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/app': typeof AppIndexRoute
  '/app/admin/auditoria': typeof AppAdminAuditoriaRoute
  '/app/admin/boletins': typeof AppAdminBoletinsRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/convites': typeof AppAdminConvitesRoute
  '/app/admin/jogos': typeof AppAdminJogosRoute
  '/app/admin/pagamentos': typeof AppAdminPagamentosRoute
  '/app/admin/perfis': typeof AppAdminPerfisRoute
  '/app/admin/premiacao': typeof AppAdminPremiacaoRoute
  '/app/admin/relatorios': typeof AppAdminRelatoriosRoute
  '/app/admin/reportes': typeof AppAdminReportesRoute
  '/app/admin/saude': typeof AppAdminSaudeRoute
  '/app/pagamento/$quota_id': typeof AppPagamentoQuota_idRoute
  '/app/palpites/top4': typeof AppPalpitesTop4Route
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/boletins': typeof AppBoletinsRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/palpites': typeof AppPalpitesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/premio': typeof AppPremioRoute
  '/app/quotas': typeof AppQuotasRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/simulador': typeof AppSimuladorRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/auditoria': typeof AppAdminAuditoriaRoute
  '/app/admin/boletins': typeof AppAdminBoletinsRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/convites': typeof AppAdminConvitesRoute
  '/app/admin/jogos': typeof AppAdminJogosRoute
  '/app/admin/pagamentos': typeof AppAdminPagamentosRoute
  '/app/admin/perfis': typeof AppAdminPerfisRoute
  '/app/admin/premiacao': typeof AppAdminPremiacaoRoute
  '/app/admin/relatorios': typeof AppAdminRelatoriosRoute
  '/app/admin/reportes': typeof AppAdminReportesRoute
  '/app/admin/saude': typeof AppAdminSaudeRoute
  '/app/pagamento/$quota_id': typeof AppPagamentoQuota_idRoute
  '/app/palpites_/top4': typeof AppPalpitesTop4Route
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/esqueci-senha'
    | '/login'
    | '/manutencao'
    | '/redefinir-senha'
    | '/app/admin'
    | '/app/boletins'
    | '/app/jogos'
    | '/app/palpites'
    | '/app/perfil'
    | '/app/premio'
    | '/app/quotas'
    | '/app/ranking'
    | '/app/simulador'
    | '/cadastro/$token'
    | '/app/'
    | '/app/admin/auditoria'
    | '/app/admin/boletins'
    | '/app/admin/configuracoes'
    | '/app/admin/convites'
    | '/app/admin/jogos'
    | '/app/admin/pagamentos'
    | '/app/admin/perfis'
    | '/app/admin/premiacao'
    | '/app/admin/relatorios'
    | '/app/admin/reportes'
    | '/app/admin/saude'
    | '/app/pagamento/$quota_id'
    | '/app/palpites/top4'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/manutencao'
    | '/redefinir-senha'
    | '/app/boletins'
    | '/app/jogos'
    | '/app/palpites'
    | '/app/perfil'
    | '/app/premio'
    | '/app/quotas'
    | '/app/ranking'
    | '/app/simulador'
    | '/cadastro/$token'
    | '/app'
    | '/app/admin/auditoria'
    | '/app/admin/boletins'
    | '/app/admin/configuracoes'
    | '/app/admin/convites'
    | '/app/admin/jogos'
    | '/app/admin/pagamentos'
    | '/app/admin/perfis'
    | '/app/admin/premiacao'
    | '/app/admin/relatorios'
    | '/app/admin/reportes'
    | '/app/admin/saude'
    | '/app/pagamento/$quota_id'
    | '/app/palpites/top4'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/esqueci-senha'
    | '/login'
    | '/manutencao'
    | '/redefinir-senha'
    | '/app/admin'
    | '/app/boletins'
    | '/app/jogos'
    | '/app/palpites'
    | '/app/perfil'
    | '/app/premio'
    | '/app/quotas'
    | '/app/ranking'
    | '/app/simulador'
    | '/cadastro/$token'
    | '/app/'
    | '/app/admin/auditoria'
    | '/app/admin/boletins'
    | '/app/admin/configuracoes'
    | '/app/admin/convites'
    | '/app/admin/jogos'
    | '/app/admin/pagamentos'
    | '/app/admin/perfis'
    | '/app/admin/premiacao'
    | '/app/admin/relatorios'
    | '/app/admin/reportes'
    | '/app/admin/saude'
    | '/app/pagamento/$quota_id'
    | '/app/palpites_/top4'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  ManutencaoRoute: typeof ManutencaoRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  CadastroTokenRoute: typeof CadastroTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/cadastro/$token': {
      id: '/cadastro/$token'
      path: '/cadastro/$token'
      fullPath: '/cadastro/$token'
      preLoaderRoute: typeof CadastroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/simulador': {
      id: '/app/simulador'
      path: '/simulador'
      fullPath: '/app/simulador'
      preLoaderRoute: typeof AppSimuladorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ranking': {
      id: '/app/ranking'
      path: '/ranking'
      fullPath: '/app/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotas': {
      id: '/app/quotas'
      path: '/quotas'
      fullPath: '/app/quotas'
      preLoaderRoute: typeof AppQuotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premio': {
      id: '/app/premio'
      path: '/premio'
      fullPath: '/app/premio'
      preLoaderRoute: typeof AppPremioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/palpites': {
      id: '/app/palpites'
      path: '/palpites'
      fullPath: '/app/palpites'
      preLoaderRoute: typeof AppPalpitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jogos': {
      id: '/app/jogos'
      path: '/jogos'
      fullPath: '/app/jogos'
      preLoaderRoute: typeof AppJogosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/boletins': {
      id: '/app/boletins'
      path: '/boletins'
      fullPath: '/app/boletins'
      preLoaderRoute: typeof AppBoletinsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/palpites_/top4': {
      id: '/app/palpites_/top4'
      path: '/palpites/top4'
      fullPath: '/app/palpites/top4'
      preLoaderRoute: typeof AppPalpitesTop4RouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pagamento/$quota_id': {
      id: '/app/pagamento/$quota_id'
      path: '/pagamento/$quota_id'
      fullPath: '/app/pagamento/$quota_id'
      preLoaderRoute: typeof AppPagamentoQuota_idRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/saude': {
      id: '/app/admin/saude'
      path: '/saude'
      fullPath: '/app/admin/saude'
      preLoaderRoute: typeof AppAdminSaudeRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/reportes': {
      id: '/app/admin/reportes'
      path: '/reportes'
      fullPath: '/app/admin/reportes'
      preLoaderRoute: typeof AppAdminReportesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/relatorios': {
      id: '/app/admin/relatorios'
      path: '/relatorios'
      fullPath: '/app/admin/relatorios'
      preLoaderRoute: typeof AppAdminRelatoriosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/premiacao': {
      id: '/app/admin/premiacao'
      path: '/premiacao'
      fullPath: '/app/admin/premiacao'
      preLoaderRoute: typeof AppAdminPremiacaoRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/perfis': {
      id: '/app/admin/perfis'
      path: '/perfis'
      fullPath: '/app/admin/perfis'
      preLoaderRoute: typeof AppAdminPerfisRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/pagamentos': {
      id: '/app/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/admin/pagamentos'
      preLoaderRoute: typeof AppAdminPagamentosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/jogos': {
      id: '/app/admin/jogos'
      path: '/jogos'
      fullPath: '/app/admin/jogos'
      preLoaderRoute: typeof AppAdminJogosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/convites': {
      id: '/app/admin/convites'
      path: '/convites'
      fullPath: '/app/admin/convites'
      preLoaderRoute: typeof AppAdminConvitesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/configuracoes': {
      id: '/app/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/admin/configuracoes'
      preLoaderRoute: typeof AppAdminConfiguracoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/boletins': {
      id: '/app/admin/boletins'
      path: '/boletins'
      fullPath: '/app/admin/boletins'
      preLoaderRoute: typeof AppAdminBoletinsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/auditoria': {
      id: '/app/admin/auditoria'
      path: '/auditoria'
      fullPath: '/app/admin/auditoria'
      preLoaderRoute: typeof AppAdminAuditoriaRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditoriaRoute: typeof AppAdminAuditoriaRoute
  AppAdminBoletinsRoute: typeof AppAdminBoletinsRoute
  AppAdminConfiguracoesRoute: typeof AppAdminConfiguracoesRoute
  AppAdminConvitesRoute: typeof AppAdminConvitesRoute
  AppAdminJogosRoute: typeof AppAdminJogosRoute
  AppAdminPagamentosRoute: typeof AppAdminPagamentosRoute
  AppAdminPerfisRoute: typeof AppAdminPerfisRoute
  AppAdminPremiacaoRoute: typeof AppAdminPremiacaoRoute
  AppAdminRelatoriosRoute: typeof AppAdminRelatoriosRoute
  AppAdminReportesRoute: typeof AppAdminReportesRoute
  AppAdminSaudeRoute: typeof AppAdminSaudeRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditoriaRoute: AppAdminAuditoriaRoute,
  AppAdminBoletinsRoute: AppAdminBoletinsRoute,
  AppAdminConfiguracoesRoute: AppAdminConfiguracoesRoute,
  AppAdminConvitesRoute: AppAdminConvitesRoute,
  AppAdminJogosRoute: AppAdminJogosRoute,
  AppAdminPagamentosRoute: AppAdminPagamentosRoute,
  AppAdminPerfisRoute: AppAdminPerfisRoute,
  AppAdminPremiacaoRoute: AppAdminPremiacaoRoute,
  AppAdminRelatoriosRoute: AppAdminRelatoriosRoute,
  AppAdminReportesRoute: AppAdminReportesRoute,
  AppAdminSaudeRoute: AppAdminSaudeRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBoletinsRoute: typeof AppBoletinsRoute
  AppJogosRoute: typeof AppJogosRoute
  AppPalpitesRoute: typeof AppPalpitesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPremioRoute: typeof AppPremioRoute
  AppQuotasRoute: typeof AppQuotasRoute
  AppRankingRoute: typeof AppRankingRoute
  AppSimuladorRoute: typeof AppSimuladorRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPagamentoQuota_idRoute: typeof AppPagamentoQuota_idRoute
  AppPalpitesTop4Route: typeof AppPalpitesTop4Route
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBoletinsRoute: AppBoletinsRoute,
  AppJogosRoute: AppJogosRoute,
  AppPalpitesRoute: AppPalpitesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPremioRoute: AppPremioRoute,
  AppQuotasRoute: AppQuotasRoute,
  AppRankingRoute: AppRankingRoute,
  AppSimuladorRoute: AppSimuladorRoute,
  AppIndexRoute: AppIndexRoute,
  AppPagamentoQuota_idRoute: AppPagamentoQuota_idRoute,
  AppPalpitesTop4Route: AppPalpitesTop4Route,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  ManutencaoRoute: ManutencaoRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  CadastroTokenRoute: CadastroTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
