/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSimuladorRouteImport } from './routes/app.simulador'
import { Route as AppRankingRouteImport } from './routes/app.ranking'
import { Route as AppQuotasRouteImport } from './routes/app.quotas'
import { Route as AppPremioRouteImport } from './routes/app.premio'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppPalpitesRouteImport } from './routes/app.palpites'
import { Route as AppJogosRouteImport } from './routes/app.jogos'
import { Route as AppBoletinsRouteImport } from './routes/app.boletins'
import { Route as AppPalpitesTop4RouteImport } from './routes/app.palpites.top4'
import { Route as AppPagamentoQuota_idRouteImport } from './routes/app.pagamento.$quota_id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSimuladorRoute = AppSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotasRoute = AppQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => AppRoute,
} as any)
const AppPremioRoute = AppPremioRouteImport.update({
  id: '/premio',
  path: '/premio',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPalpitesRoute = AppPalpitesRouteImport.update({
  id: '/palpites',
  path: '/palpites',
  getParentRoute: () => AppRoute,
} as any)
const AppJogosRoute = AppJogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => AppRoute,
} as any)
const AppBoletinsRoute = AppBoletinsRouteImport.update({
  id: '/boletins',
  path: '/boletins',
  getParentRoute: () => AppRoute,
} as any)
const AppPalpitesTop4Route = AppPalpitesTop4RouteImport.update({
  id: '/top4',
  path: '/top4',
  getParentRoute: () => AppPalpitesRoute,
} as any)
const AppPagamentoQuota_idRoute = AppPagamentoQuota_idRouteImport.update({
  id: '/pagamento/$quota_id',
  path: '/pagamento/$quota_id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/boletins': typeof AppBoletinsRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/palpites': typeof AppPalpitesRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/premio': typeof AppPremioRoute
  '/app/quotas': typeof AppQuotasRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/simulador': typeof AppSimuladorRoute
  '/app/': typeof AppIndexRoute
  '/app/pagamento/$quota_id': typeof AppPagamentoQuota_idRoute
  '/app/palpites/top4': typeof AppPalpitesTop4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/boletins': typeof AppBoletinsRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/palpites': typeof AppPalpitesRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/premio': typeof AppPremioRoute
  '/app/quotas': typeof AppQuotasRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/simulador': typeof AppSimuladorRoute
  '/app': typeof AppIndexRoute
  '/app/pagamento/$quota_id': typeof AppPagamentoQuota_idRoute
  '/app/palpites/top4': typeof AppPalpitesTop4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/boletins': typeof AppBoletinsRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/palpites': typeof AppPalpitesRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/premio': typeof AppPremioRoute
  '/app/quotas': typeof AppQuotasRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/simulador': typeof AppSimuladorRoute
  '/app/': typeof AppIndexRoute
  '/app/pagamento/$quota_id': typeof AppPagamentoQuota_idRoute
  '/app/palpites/top4': typeof AppPalpitesTop4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/boletins'
    | '/app/jogos'
    | '/app/palpites'
    | '/app/perfil'
    | '/app/premio'
    | '/app/quotas'
    | '/app/ranking'
    | '/app/simulador'
    | '/app/'
    | '/app/pagamento/$quota_id'
    | '/app/palpites/top4'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/boletins'
    | '/app/jogos'
    | '/app/palpites'
    | '/app/perfil'
    | '/app/premio'
    | '/app/quotas'
    | '/app/ranking'
    | '/app/simulador'
    | '/app'
    | '/app/pagamento/$quota_id'
    | '/app/palpites/top4'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/boletins'
    | '/app/jogos'
    | '/app/palpites'
    | '/app/perfil'
    | '/app/premio'
    | '/app/quotas'
    | '/app/ranking'
    | '/app/simulador'
    | '/app/'
    | '/app/pagamento/$quota_id'
    | '/app/palpites/top4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulador': {
      id: '/app/simulador'
      path: '/simulador'
      fullPath: '/app/simulador'
      preLoaderRoute: typeof AppSimuladorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ranking': {
      id: '/app/ranking'
      path: '/ranking'
      fullPath: '/app/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotas': {
      id: '/app/quotas'
      path: '/quotas'
      fullPath: '/app/quotas'
      preLoaderRoute: typeof AppQuotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premio': {
      id: '/app/premio'
      path: '/premio'
      fullPath: '/app/premio'
      preLoaderRoute: typeof AppPremioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/palpites': {
      id: '/app/palpites'
      path: '/palpites'
      fullPath: '/app/palpites'
      preLoaderRoute: typeof AppPalpitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jogos': {
      id: '/app/jogos'
      path: '/jogos'
      fullPath: '/app/jogos'
      preLoaderRoute: typeof AppJogosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/boletins': {
      id: '/app/boletins'
      path: '/boletins'
      fullPath: '/app/boletins'
      preLoaderRoute: typeof AppBoletinsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/palpites/top4': {
      id: '/app/palpites/top4'
      path: '/top4'
      fullPath: '/app/palpites/top4'
      preLoaderRoute: typeof AppPalpitesTop4RouteImport
      parentRoute: typeof AppPalpitesRoute
    }
    '/app/pagamento/$quota_id': {
      id: '/app/pagamento/$quota_id'
      path: '/pagamento/$quota_id'
      fullPath: '/app/pagamento/$quota_id'
      preLoaderRoute: typeof AppPagamentoQuota_idRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPalpitesRouteChildren {
  AppPalpitesTop4Route: typeof AppPalpitesTop4Route
}

const AppPalpitesRouteChildren: AppPalpitesRouteChildren = {
  AppPalpitesTop4Route: AppPalpitesTop4Route,
}

const AppPalpitesRouteWithChildren = AppPalpitesRoute._addFileChildren(
  AppPalpitesRouteChildren,
)

interface AppRouteChildren {
  AppBoletinsRoute: typeof AppBoletinsRoute
  AppJogosRoute: typeof AppJogosRoute
  AppPalpitesRoute: typeof AppPalpitesRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppPremioRoute: typeof AppPremioRoute
  AppQuotasRoute: typeof AppQuotasRoute
  AppRankingRoute: typeof AppRankingRoute
  AppSimuladorRoute: typeof AppSimuladorRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPagamentoQuota_idRoute: typeof AppPagamentoQuota_idRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoletinsRoute: AppBoletinsRoute,
  AppJogosRoute: AppJogosRoute,
  AppPalpitesRoute: AppPalpitesRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppPremioRoute: AppPremioRoute,
  AppQuotasRoute: AppQuotasRoute,
  AppRankingRoute: AppRankingRoute,
  AppSimuladorRoute: AppSimuladorRoute,
  AppIndexRoute: AppIndexRoute,
  AppPagamentoQuota_idRoute: AppPagamentoQuota_idRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
